"""
SecureAI X — PDF Report Generator
Builds a downloadable security assessment report from scan results.
"""

import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

DARK = colors.HexColor("#0a0f0d")
GREEN = colors.HexColor("#00c97a")
CRIT = colors.HexColor("#ff4d4d")
HIGH = colors.HexColor("#ff9f43")
MED = colors.HexColor("#ffd93d")
LOW = colors.HexColor("#6fbfff")
MUTED = colors.HexColor("#5c6b66")

SEV_COLOR = {"critical": CRIT, "high": HIGH, "medium": MED, "low": LOW}


def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(name="Brand", fontSize=22, textColor=GREEN,
                           fontName="Helvetica-Bold", spaceAfter=2))
    ss.add(ParagraphStyle(name="SubBrand", fontSize=10, textColor=MUTED,
                           fontName="Helvetica", spaceAfter=14))
    ss.add(ParagraphStyle(name="H2", fontSize=13, textColor=colors.HexColor("#0a0f0d"),
                           fontName="Helvetica-Bold", spaceBefore=14, spaceAfter=6))
    ss.add(ParagraphStyle(name="Body9", fontSize=9, leading=13,
                           fontName="Helvetica", textColor=colors.HexColor("#222")))
    ss.add(ParagraphStyle(name="Mono8", fontSize=8, leading=11,
                           fontName="Courier", textColor=colors.HexColor("#333")))
    return ss


def build_report_pdf(filename: str, risk: dict, findings: list) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=18 * mm, bottomMargin=16 * mm,
        leftMargin=16 * mm, rightMargin=16 * mm,
        title="SecureAI X Security Report",
    )
    ss = _styles()
    story = []

    story.append(Paragraph("SECUREAI X", ss["Brand"]))
    story.append(Paragraph("AI-Assisted Static Application Security Report", ss["SubBrand"]))
    story.append(HRFlowable(width="100%", color=GREEN, thickness=1))
    story.append(Spacer(1, 10))

    meta = [
        ["Target file", filename],
        ["Scan date", datetime.now().strftime("%Y-%m-%d %H:%M")],
        ["Security score", f"{risk['score']} / 100  ({risk['label']})"],
        ["Total findings", str(risk["total_findings"])],
    ]
    t = Table(meta, colWidths=[45 * mm, 120 * mm])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))

    counts = risk["counts"]
    sev_row = [
        [Paragraph(f'<font color="{CRIT.hexval()}"><b>{counts["critical"]}</b></font> Critical', ss["Body9"]),
         Paragraph(f'<font color="{HIGH.hexval()}"><b>{counts["high"]}</b></font> High', ss["Body9"]),
         Paragraph(f'<font color="{MED.hexval()}"><b>{counts["medium"]}</b></font> Medium', ss["Body9"]),
         Paragraph(f'<font color="{LOW.hexval()}"><b>{counts["low"]}</b></font> Low', ss["Body9"])]
    ]
    st = Table(sev_row, colWidths=[41 * mm] * 4)
    st.setStyle(TableStyle([("BOTTOMPADDING", (0, 0), (-1, -1), 8)]))
    story.append(st)

    story.append(Paragraph("Findings", ss["H2"]))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#dddddd"), thickness=0.5))

    if not findings:
        story.append(Paragraph("No vulnerabilities detected by the current rule set.", ss["Body9"]))
    else:
        for f in findings:
            sev = f["severity"]
            color = SEV_COLOR.get(sev, MUTED)
            header = Paragraph(
                f'<b>{f["id"]} — {f["type"]}</b>  '
                f'<font color="{color.hexval()}">[{sev.upper()}]</font>  '
                f'<font color="{MUTED.hexval()}">line {f["line"]} · {f["cwe"]} · '
                f'{f["confidence"]}% confidence</font>',
                ss["Body9"],
            )
            snippet = Paragraph(f'<font face="Courier">{_escape(f["snippet"])}</font>', ss["Mono8"])
            desc = Paragraph(f'<b>Risk:</b> {f["description"]}', ss["Body9"])
            fix = Paragraph(f'<b>Fix:</b> {f["recommendation"]}', ss["Body9"])
            story.extend([header, Spacer(1, 2), snippet, Spacer(1, 3), desc, fix, Spacer(1, 8)])

    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", color=GREEN, thickness=1))
    story.append(Paragraph(
        "Generated by SecureAI X — for educational and pre-deployment review purposes. "
        "Not a substitute for professional penetration testing.",
        ss["SubBrand"],
    ))

    doc.build(story)
    return buf.getvalue()


def _escape(text: str) -> str:
    return (text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
